apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back-${params.Branch}
spec:
  selector:
    matchLabels:
      app: azure-vote-back-${params.Branch}
  template:
    metadata:
      labels:
        app: azure-vote-back-${params.Branch}
    spec:
      containers:
      - name: azure-vote-back-${params.Branch}
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back-${params.Branch}
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back-${params.Branch}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front-${params.Branch}
spec:
  selector:
    matchLabels:
      app: azure-vote-front-${params.Branch}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-vote-front-${params.Branch}
    spec:
      containers:
      - name: azure-vote-front-${params.Branch}
        image: docker pull rgzanjenkinsregistry.azurecr.io/azure-voting-app-redis-green:${BUILD_NUMBER}
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front-${params.Branch}
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front-${params.Branch}
