apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-vote-deployment-${TARGET_ROLE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-voting-app-redis-${TARGET_ROLE}
        role: ${TARGET_ROLE}
    spec:
      containers:
      - name:azure-voting-app-redi-container
        image: ${IMAGE_TAG}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      imagePullSecrets:
      - name: ${KUBERNETES_SECRET_NAME}
